[build]
  command = "npm run build"
  publish = "dist/spa"
  functions = "netlify/functions"

# Proxy API requests to the Netlify function (Express app wrapped with serverless-http)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

# SPA fallback to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
